name: "BIO-wijzigingsverzoek"
description: "Dank je wel voor het indienen van een BIO-wijzigingsverzoek."
assignees:
  - BartL-CIP
labels:
  - wijzigingsvoorstel
body:
  - type: markdown
    attributes:
      value: Noteer het hoofdstuk- of paragraafnummer, gevolgd door een dubbele punt en daarna een korte samenvatting van het BIO-wijzigingsverzoek. Gaat het om een toevoeging van een hoofdstuk of paragraaf start met Algemeen.

  - type: checkboxes
    id: welk_deel_van_de_BIO
    attributes:
      label: Welk deel van de BIO of het BIO-ontwerp
      description: Bijvoorbeeld de Voortekst. Hiermee worden de ongenummerde hoofdstukken bedoeld (voorblad, copyright-notitie, wijzigingsbeheer en dankwoord).
      options:
        - label: Voortekst
        - label: Deel 1 BIO2-kader
        - label: Deel 2 BIO-overheidsmaatregelen
        - label: BIO-ontwerp
        - label: Algemeen
    validations:
      required: true
      
  - type: input
    id: bio_version
    attributes:
      label: BIO-versie of BIO-ontwerpversie
      description: Noteer het versienummer van de BIO of het BIO-ontwerp waarop het BIO-wijzigingsverzoek betrekking heeft. De laatste versie van de BIO is de BIO2 v1.3.
      value: BIO2 v1.3
    validations:
      required: true

  - type: input
    id: identificatienummer
    attributes:
      label: Identificatienummer(s) + titel(s)
      description: Noteer het nummer van het hoofdstuk + titel, de paragraaf + titel, de overheidsmaatregel etc., waarhet BIO-wijzigingsverzoek betrekking op heeft. Voeg eventueel regelnummer(s) of de betreffende alinea(s) toe.
    validations:
      required: true

  - type: textarea
    id: argumentatie
    attributes:
      label: Constatering + argumentatie
      description: Noteer de constatering en de argumentatie voor het BIO-wijzigingsverzoek, denk aan feitelijke onjuistheden, inconsitentie tekst, veranderde wet- en regelgeving, BIO onderhoudsarmer maken etc.
      render: text
    validations:
      required: true

  - type: textarea
    id: huidige_tekst
    attributes:
      label: Huidige tekst
      description: Noteer de huidige tekst uit de BIO of uit het BIO-ontwerp.
      render: text

  - type: textarea
    id: voorgestelde_tekst
    attributes:
      label: Voorgestelde tekst
      description: Noteer de voorgestelde tekst.
      render: text
    validations:
      required: true
 
  - type: textarea
    id: verwachte_impact
    attributes:
      label: Verwachte impact
      description: Noteer eventueel de verwachte positieve en negatieve impact. Denk aan middelen per overheidslaag, aanpassen van processen per overheidslaag, capaciteit per overheidslaag etc.
      render: text

  - type: textarea
    id: opmerkingen
    attributes:
      label: Opmerkingen
      description: Noteer eventuele opmerkingen of aanvullende informatie, zoals een toelichting, links en/of bijlagen.
      render: text
