name: "BIO-wijzigingsverzoek"
description: "Dank je wel voor het indienen van een BIO-wijzigingsverzoek."
assignees:
  - BartL-CIP
labels:
  - wijzigingsvoorstel
body:
  - type: markdown
    attributes:
      value: Noteer het hoofdstuk-, paragraaf- of maatregelnummer, gevolgd door een dubbele punt en daarna een korte samenvatting van het wijzigingsverzoek. 

  - type: checkboxes
    id: welk_deel_van_de_BIO
    attributes:
      label: Welk deel van de BIO heeft je verzoek betrekking op?
      description: Bijvoorbeeld de Voortekst. Hiermee worden de ongenummerde hoofdstukken bedoeld (voorblad, copyright-notitie, wijzigingsbeheer en dankwoord).
      options:
        - label: Voortekst 
        - label: Deel 1 BIO2-kader
        - label: Deel 2 BIO-overheidsmaatregelen
        - label: BIO-ontwerp
        - label: Algemeen/Overig
    validations:
      required: true
      
  - type: input
    id: bio_version
    attributes:
      label: BIO-versie of BIO-ontwerpversie
      description: Noteer het versienummer waarop het verzoek betrekking heeft. De huidige versie is BIO2 v1.3.
      value: BIO2 v1.3
    validations:
      required: true

  - type: input
    id: identificatienummer
    attributes:
      label: Identificatienummer(s) + titel(s)
      description: Noteer het nummer van het hoofdstuk, de paragraaf en/of de overheidsmaatregel waar het verzoek betrekking op heeft. 
    validations:
      required: true

  - type: textarea
    id: argumentatie
    attributes:
      label: Constatering + motivatie
      description: Noteer de constatering en motivatie voor het verzoek. Denk aan feitelijke onjuistheden, inconsitentie tekst, veranderde wet- en regelgeving, nieuwe ontwikkelingen etc.
      render: text
    validations:
      required: true

  - type: textarea
    id: huidige_tekst
    attributes:
      label: Huidige tekst
      description: Noteer de huidige tekst uit de BIO of uit het BIO-ontwerp.
      render: text

  - type: textarea
    id: voorgestelde_tekst
    attributes:
      label: Voorgestelde tekst
      description: Noteer de voorgestelde tekst.
      render: text
    validations:
      required: true
 
  - type: textarea
    id: verwachte_impact
    attributes:
      label: Verwachte impact
      description: Noteer de eventuele verwachte positieve en negatieve impact. Denk aan middelen per overheidslaag, aanpassen van processen per overheidslaag, capaciteit per overheidslaag etc.
      render: text

  - type: textarea
    id: opmerkingen
    attributes:
      label: Opmerkingen
      description: Noteer eventuele opmerkingen of aanvullende informatie, zoals een toelichting, links en/of bijlagen.
      render: text


Dit wijzigingsverzoek wordt openbaar gepubliceerd(GitHub). Vermeld daarom geen onnodige persoonsgegevens van jezelf of anderen in het verzoek.
Je GitHub-accountnaam en andere gegevens die je zelf openbaar maakt, kunnen zichtbaar blijven als onderdeel van het wijzigingsverzoek en de wijzigingshistorie.
